version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: library_db
    restart: unless-stopped
    hostname: library_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d  # Mount SQL scripts
      - mysql_data:/var/lib/mysql   # Mount a volume to persist MySQL data
    networks:
      - library_network

  library_api:
    build: ./library-api
    ports:
      - "3009:3009"
    depends_on:
      - mysql
    networks:
      - library_network
networks:
  library_network:
    driver: bridge

volumes:
  mysql_data:  # Define a named volume for MySQL data persistence
