name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]  # Change to your desired branch to trigger on push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t library_api ./library-api

      - name: Push Docker image (Optional)
        uses: docker/push-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: your_username/library_api  # Replace with your username/repo
        # This step is optional if you don't want to push to a Docker registry

      - name: Deploy to Droplet
        run: |
          doctl kubernetes cluster kubeconfig save my-cluster  # Replace with your cluster name
          docker-compose -H "my-cluster:8080" up -d  # Adjust hostname/port if needed
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
